#!/bin/sh

# Generate a random string

function random() {
  if [ -z "${1}" ]; then
      echo "ERROR: Specify amount of random characters to generate.";
      return 1;
  fi;

  LC_ALL=C tr -dc 'A-Za-z0-9!"#$%&'\''()*+,-./:;<=>?@[\]^_`{|}~' </dev/urandom | head -c $1 ; echo 
}