#!/usr/bin/env bash
set -e

export ZSH="$HOME/.dotfiles"
export DOTFILES_ROOT="$HOME/.dotfiles"

cd "$ZSH"

for src in $(find -H "$DOTFILES_ROOT" -maxdepth 2 -name '*.symlink' -not -path '*.git*')
  do
    dst="$HOME/.$(basename "${src%.*}")"
    rm -rf "$dst"
    ln -s "$src" "$dst"
  done

$DOTFILES_ROOT/macos/set-defaults.sh

