#!/usr/bin/env bash
set -e

export DOTFILES="$HOME/.dotfiles"

cd "$DOTFILES"

for src in $(find -H "$DOTFILES" -maxdepth 2 -name '*.symlink' -not -path '*.git*')
  do
    dst="$HOME/.$(basename "${src%.*}")"
    rm -rf "$dst"
    ln -s "$src" "$dst"
  done

$DOTFILES/macos/set-defaults.sh
