cask_args appdir: '~/Applications'

tap 'homebrew/bundle'

brew 'watchman'
brew 'ack'
brew 'coreutils'
brew 'grc'
brew 'openssl'
brew 'wget'
brew 'yarn', args: ["ignore-dependencies"]
brew 'ffmpeg'

cask 'docker'
cask 'firefox'
cask 'google-chrome'
cask 'slack'
cask 'spotify'
cask 'visual-studio-code'
cask 'zoom'
cask 'mongodb-compass'