#!/usr/bin/env bash
set -e

# Run all dotfiles installers.

cd "$(dirname $0)"/..

# find the installers and run them iteratively
find . -name install.sh | while read installer ; do 
  echo ":: ${installer} ::"
  echo "====================="
  sh -c "${installer}" >/dev/stderr | sed 's/1/2/';

  done
